fail_on_violations: true

flake8:
  enabled: true
  config_file: backend/uclapi/.flake8.ini

eslint:
  enabled: true
  config_file: uclapi-frontend/.eslintrc.json
  ignore_file: frontend/.prettierignore
