fail_on_violations: true

flake8:
  enabled: true
  config_file: backend/uclapi/.flake8.ini

scss:
  enabled: true
  config_file: frontend/.stylelintrc.yml

eslint:
  enabled: true
  config_file: frontend/.eslintrc.hound.json
  ignore_file: frontend/.eslintignore
  version: 6.3.0
