version: '3.7'

services:
  db:
    image: postgres:11.1
    restart: always
    environment:
        POSTGRES_USER: uclapi
        POSTGRES_PASSWORD: uclapi_test_password
        POSTGRES_DB: uclapi
    volumes:
      - type: volume
        source: uclapi-db
        target: /var/lib/postgresql/data
  gencache:
    image: postgres:11.1
    restart: always
    environment:
        POSTGRES_USER: uclapi_gencache
        POSTGRES_PASSWORD: uclapi_gencache_test_password
        POSTGRES_DB: uclapi_gencache
    volumes:
      - type: volume
        source: uclapi-gencache
        target: /var/lib/postgresql/data
  redis: 
    image: redis:alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - type: volume
        source: uclapi-redis
        target: /data
  uclapi:
    build:
      context: .
      dockerfile: docker/uclapi-dev.Dockerfile
    volumes:
      - type: bind
        source: .
        target: /web/uclapi
        read_only: true
    ports:
      - "8000:8000"
    depends_on:
      - db
      - gencache
      - redis
    env_file:
      # allow setting of some env variables and fallback
      # to example file for default values
      - ./backend/uclapi/.env.docker.example
      - ./backend/uclapi/.env
    environment:
      # DB/Redis-specific variables should be fixed
      - DB_UCLAPI_NAME=uclapi
      - DB_UCLAPI_USERNAME=uclapi
      - DB_UCLAPI_PASSWORD=uclapi_test_password
      - DB_UCLAPI_HOST=db
      - DB_UCLAPI_PORT=5432
      - DB_CACHE_NAME=uclapi_gencache
      - DB_CACHE_USERNAME=uclapi_gencache
      - DB_CACHE_PASSWORD=uclapi_gencache_test_password
      - DB_CACHE_HOST=gencache
      - DB_CACHE_PORT=5432
      - REDIS_UCLAPI_HOST=redis


  fakeshibboleth:
    build:
      context: .
      dockerfile: docker/fakeshibboleth.Dockerfile
      args:
        AUTO_EPPN: develop@ucl.ac.uk
        AUTO_UCLINTRANETGROUPS: ucl-all;ucl-ug;schsci-all
        AUTO_CN: develop
        AUTO_DEPARTMENT: Dept of API Development
        AUTO_GIVENNAME: UCL API
        AUTO_DISPLAYNAME: UCL API Developer
        AUTO_EMPLOYEEID: uclapi1
        AUTO_AFFILIATION: member@ucl.ac.uk;student@ucl.ac.uk
        AUTO_MAIL: ucl.api.developer@ucl.ac.uk
        AUTO_SN: Developer
        AUTO_UNSCOPED_AFFILIATION: student;member
    ports:
      - "8001:8001"
  oauth-test:
    build:
      context: .
      dockerfile: docker/oauth-test.Dockerfile
      args:
        UCLAPI_CLIENT_ID: '1105308584328350.9460393713696551'
        UCLAPI_CLIENT_SECRET: 251e9f9553bb3b86829c18bf795844d977dedf569b24a70e4d4e753958fcc2f3
    ports:
      - "8002:8002"

volumes:
  uclapi-db:
  uclapi-gencache:
  uclapi-redis:
