version: '3.7'

services:
  db:
    image: postgres:11.1
    restart: always
    environment:
        POSTGRES_USER: uclapi
        POSTGRES_PASSWORD: uclapi_test_password
        POSTGRES_DB: uclapi
    volumes:
      - type: volume
        source: uclapi-db
        target: /var/lib/postgresql/data
  gencache:
    image: postgres:11.1
    restart: always
    environment:
        POSTGRES_USER: uclapi_gencache
        POSTGRES_PASSWORD: uclapi_gencache_test_password
        POSTGRES_DB: uclapi_gencache
    volumes:
      - type: volume
        source: uclapi-gencache
        target: /var/lib/postgresql/data
  redis: 
    image: redis:alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - type: volume
        source: uclapi-redis
        target: /data
  uclapi:
    build:
      context: .
      dockerfile: docker/uclapi-dev.Dockerfile
    volumes:
      - type: bind
        source: .
        target: /web/uclapi
        read_only: true
    ports:
      - "8000:8000"
    depends_on:
      - db
      - gencache
      - redis
    env_file:
      - ./backend/uclapi/.env
    environment:
      - SECRET_KEY=iRlsWf2BF2nnNy1zIsZcun6fZX5GGpk0
      - UCLAPI_PRODUCTION=False
      - UCLAPI_DOMAIN=localhost:8000
      - UCLAPI_RUNNING_ON_AWS_ELB=False
      - UCLAPI_CALLBACK_ALLOWED_PROTOCOLS=https;http
      - DB_UCLAPI_NAME=uclapi
      - DB_UCLAPI_USERNAME=uclapi
      - DB_UCLAPI_PASSWORD=uclapi_test_password
      - DB_UCLAPI_HOST=db
      - DB_UCLAPI_PORT=5432
      - DB_CACHE_NAME=uclapi_gencache
      - DB_CACHE_USERNAME=uclapi_gencache
      - DB_CACHE_PASSWORD=uclapi_gencache_test_password
      - DB_CACHE_HOST=gencache
      - DB_CACHE_PORT=5432
      - ORACLE_HOME=/opt/oracle/instantclient_12_2
      - REDIS_UCLAPI_HOST=redis
      - FORBIDDEN_CALLBACK_URLS=uclapi.com;staging.ninja
      - WHITELISTED_CALLBACK_URLS=https://live-roombookings.uclapi.com/webhook/;https://hackathon.uclapi.com/callback
      - EVENTLET_NOPATCH=True

  oauth-test:
    build:
      context: .
      dockerfile: docker/oauth-test.Dockerfile
      args:
        UCLAPI_CLIENT_ID: '1105308584328350.9460393713696551'
        UCLAPI_CLIENT_SECRET: 251e9f9553bb3b86829c18bf795844d977dedf569b24a70e4d4e753958fcc2f3
    ports:
      - "8002:8002"

volumes:
  uclapi-db:
  uclapi-gencache:
  uclapi-redis:
