version: '3.7'

services:
  db:
    image: postgres:11.1
    restart: on-failure
    environment:
        POSTGRES_USER: uclapi
        POSTGRES_PASSWORD: uclapi_test_password
        POSTGRES_DB: uclapi
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: uclapi-db
        target: /var/lib/postgresql/data

  gencache:
    image: postgres:11.1
    restart: on-failure
    environment:
        POSTGRES_USER: uclapi_gencache
        POSTGRES_PASSWORD: uclapi_gencache_test_password
        POSTGRES_DB: uclapi_gencache
    ports:
      - "5433:5432"
    volumes:
      - type: volume
        source: uclapi-gencache
        target: /var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: on-failure
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - type: volume
        source: uclapi-redis
        target: /data

volumes:
  uclapi-db:
  uclapi-gencache:
  uclapi-redis:
