# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipment',
            table='"CMIS_OWNER"."EQUIPMENT"',
        ),
    ]
