# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-05 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20171005_1918'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ccalmaps',
            table='"CMIS_OWNER"."CCALMAPS"',
        ),
        migrations.AlterModelTable(
            name='classgrps',
            table='"CMIS_OWNER"."CLASSGRPS"',
        ),
        migrations.AlterModelTable(
            name='classifications',
            table='"CMIS_OWNER"."CLASSIFICATIONS"',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='"CMIS_OWNER"."CONTACT"',
        ),
        migrations.AlterModelTable(
            name='course',
            table='"CMIS_OWNER"."COURSE"',
        ),
        migrations.AlterModelTable(
            name='crsavailmodules',
            table='"CMIS_OWNER"."CRSAVAILMODULES"',
        ),
        migrations.AlterModelTable(
            name='crscompmodules',
            table='"CMIS_OWNER"."CRSCOMPMODULES"',
        ),
        migrations.AlterModelTable(
            name='depts',
            table='"CMIS_OWNER"."DEPTS"',
        ),
        migrations.AlterModelTable(
            name='features',
            table='"CMIS_OWNER"."FEATURES"',
        ),
        migrations.AlterModelTable(
            name='lecturer',
            table='"CMIS_OWNER"."LECTURER"',
        ),
        migrations.AlterModelTable(
            name='module',
            table='"CMIS_OWNER"."MODULE"',
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='"CMIS_OWNER"."ROOMS"',
        ),
        migrations.AlterModelTable(
            name='sites',
            table='"CMIS_OWNER"."SITES"',
        ),
        migrations.AlterModelTable(
            name='slotdetails',
            table='"CMIS_OWNER"."SLOTDETAILS"',
        ),
        migrations.AlterModelTable(
            name='sources',
            table='"CMIS_OWNER"."SOURCES"',
        ),
        migrations.AlterModelTable(
            name='students',
            table='"CMIS_OWNER"."STUDENTS"',
        ),
        migrations.AlterModelTable(
            name='stumodules',
            table='"CMIS_OWNER"."STUMODULES"',
        ),
        migrations.AlterModelTable(
            name='timetable',
            table='"CMIS_OWNER"."TIMETABLE"',
        ),
        migrations.AlterModelTable(
            name='weekmapnumeric',
            table='"CMIS_OWNER"."WEEKMAPNUMERIC"',
        ),
        migrations.AlterModelTable(
            name='weekmapstring',
            table='"CMIS_OWNER"."WEEKMAPSTRING"',
        ),
        migrations.AlterModelTable(
            name='weekstructure',
            table='"CMIS_OWNER"."WEEKSTRUCTURE"',
        ),
    ]
