# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20170928_2100'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timetable',
            table="'CMIS_OWNER'.'TIMETABLE'",
        ),
    ]
