# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20170928_2101'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timetable',
            table='TIMETABLE',
        ),
    ]
