# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20171007_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptsA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deptid', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=250)),
                ('category', models.TextField(max_length=10)),
                ('type', models.TextField(max_length=10)),
                ('linkcode', models.TextField(max_length=20)),
                ('headofdepartment', models.TextField(max_length=50)),
                ('headphone', models.TextField(max_length=50)),
                ('address1', models.TextField(max_length=50)),
                ('address2', models.TextField(max_length=50)),
                ('address3', models.TextField(max_length=50)),
                ('address4', models.TextField(max_length=50)),
                ('admincontact', models.TextField(max_length=50)),
                ('adminphone', models.TextField(max_length=50)),
                ('lecturerid', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DeptsB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deptid', models.TextField(max_length=10)),
                ('name', models.TextField(max_length=250)),
                ('category', models.TextField(max_length=10)),
                ('type', models.TextField(max_length=10)),
                ('linkcode', models.TextField(max_length=20)),
                ('headofdepartment', models.TextField(max_length=50)),
                ('headphone', models.TextField(max_length=50)),
                ('address1', models.TextField(max_length=50)),
                ('address2', models.TextField(max_length=50)),
                ('address3', models.TextField(max_length=50)),
                ('address4', models.TextField(max_length=50)),
                ('admincontact', models.TextField(max_length=50)),
                ('adminphone', models.TextField(max_length=50)),
                ('lecturerid', models.TextField(max_length=10)),
            ],
        ),
    ]
