# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_cminstances_cminstancesa_cminstancesb_stumodulesa_stumodulesb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomsA',
        ),
        migrations.DeleteModel(
            name='RoomsB',
        ),
    ]
