# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable',
         '0007_cminstances_cminstancesa_cminstancesb_stumodulesa_stumodulesb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('courseid', models.TextField(max_length=12)),
                ('name', models.TextField(max_length=80)),
                ('category', models.TextField(max_length=10)),
                ('type', models.TextField(max_length=10)),
                ('linkcode', models.TextField(max_length=20)),
                ('owner', models.TextField(max_length=10)),
                ('numyears', models.BigIntegerField(blank=True, null=True)),
                ('crsweight', models.FloatField(null=True)),
                ('minmodules', models.BigIntegerField(blank=True, null=True)),
                ('maxmodules', models.BigIntegerField(blank=True, null=True)),
                ('numplaces', models.BigIntegerField(blank=True, null=True)),
                ('mintotal', models.BigIntegerField(blank=True, null=True)),
                ('maxtotal', models.BigIntegerField(blank=True, null=True)),
                ('firstyear', models.BigIntegerField(blank=True, null=True)),
                ('oldcourseid', models.TextField(max_length=12)),
                ('isactive', models.CharField(max_length=1)),
                ('lecturerid', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('courseid', models.TextField(max_length=12)),
                ('name', models.TextField(max_length=80)),
                ('category', models.TextField(max_length=10)),
                ('type', models.TextField(max_length=10)),
                ('linkcode', models.TextField(max_length=20)),
                ('owner', models.TextField(max_length=10)),
                ('numyears', models.BigIntegerField(blank=True, null=True)),
                ('crsweight', models.FloatField(null=True)),
                ('minmodules', models.BigIntegerField(blank=True, null=True)),
                ('maxmodules', models.BigIntegerField(blank=True, null=True)),
                ('numplaces', models.BigIntegerField(blank=True, null=True)),
                ('mintotal', models.BigIntegerField(blank=True, null=True)),
                ('maxtotal', models.BigIntegerField(blank=True, null=True)),
                ('firstyear', models.BigIntegerField(blank=True, null=True)),
                ('oldcourseid', models.TextField(max_length=12)),
                ('isactive', models.CharField(max_length=1)),
                ('lecturerid', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CrsavailmodulesA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('courseid', models.TextField(max_length=12)),
                ('crsyear', models.BigIntegerField(blank=True, null=True)),
                ('groupnum', models.BigIntegerField(blank=True, null=True)),
                ('deptid', models.TextField(max_length=10)),
                ('moduleid', models.TextField(max_length=12)),
                ('instid', models.BigIntegerField(blank=True, null=True)),
                ('semid', models.BigIntegerField(blank=True, null=True)),
                ('unitvalue', models.TextField(max_length=19)),
                ('crsver', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrsavailmodulesB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('courseid', models.TextField(max_length=12)),
                ('crsyear', models.BigIntegerField(blank=True, null=True)),
                ('groupnum', models.BigIntegerField(blank=True, null=True)),
                ('deptid', models.TextField(max_length=10)),
                ('moduleid', models.TextField(max_length=12)),
                ('instid', models.BigIntegerField(blank=True, null=True)),
                ('semid', models.BigIntegerField(blank=True, null=True)),
                ('unitvalue', models.TextField(max_length=19)),
                ('crsver', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrscompmodulesA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('courseid', models.TextField(max_length=12)),
                ('crsyear', models.BigIntegerField(blank=True, null=True)),
                ('deptid', models.TextField(max_length=10)),
                ('moduleid', models.TextField(max_length=12)),
                ('instid', models.BigIntegerField(blank=True, null=True)),
                ('semid', models.BigIntegerField(blank=True, null=True)),
                ('unitvalue', models.TextField(max_length=19)),
                ('crsver', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrscompmodulesB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('courseid', models.TextField(max_length=12)),
                ('crsyear', models.BigIntegerField(blank=True, null=True)),
                ('deptid', models.TextField(max_length=10)),
                ('moduleid', models.TextField(max_length=12)),
                ('instid', models.BigIntegerField(blank=True, null=True)),
                ('semid', models.BigIntegerField(blank=True, null=True)),
                ('unitvalue', models.TextField(max_length=19)),
                ('crsver', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
