# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_cminstances_cminstancesa_cminstancesb_stumodulesa_stumodulesb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulegroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setid', models.TextField(max_length=10)),
                ('moduleid', models.TextField(max_length=12)),
                ('owner', models.TextField(max_length=10)),
                ('grpcode', models.TextField(max_length=10)),
                ('name', models.TextField(blank=True, max_length=30, null=True)),
                ('csize', models.IntegerField()),
                ('minsize', models.IntegerField()),
                ('maxsize', models.IntegerField()),
                ('prefmaxsize', models.IntegerField()),
                ('linkcode', models.TextField(blank=True, max_length=20, null=True)),
                ('estsize', models.IntegerField()),
                ('thiskey', models.IntegerField()),
                ('parentkey', models.IntegerField()),
                ('groupnum', models.IntegerField()),
                ('mequivid', models.IntegerField()),
                ('instid', models.IntegerField()),
            ],
            options={
                'db_table': '"CMIS_OWNER"."MODULEGROUPS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModulegroupsA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('moduleid', models.TextField(max_length=12)),
                ('owner', models.TextField(max_length=10)),
                ('grpcode', models.TextField(max_length=10)),
                ('name', models.TextField(blank=True, max_length=30, null=True)),
                ('csize', models.IntegerField()),
                ('minsize', models.IntegerField()),
                ('maxsize', models.IntegerField()),
                ('prefmaxsize', models.IntegerField()),
                ('linkcode', models.TextField(blank=True, max_length=20, null=True)),
                ('estsize', models.IntegerField()),
                ('thiskey', models.IntegerField()),
                ('parentkey', models.IntegerField()),
                ('groupnum', models.IntegerField()),
                ('mequivid', models.IntegerField()),
                ('instid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ModulegroupsB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('moduleid', models.TextField(max_length=12)),
                ('owner', models.TextField(max_length=10)),
                ('grpcode', models.TextField(max_length=10)),
                ('name', models.TextField(blank=True, max_length=30, null=True)),
                ('csize', models.IntegerField()),
                ('minsize', models.IntegerField()),
                ('maxsize', models.IntegerField()),
                ('prefmaxsize', models.IntegerField()),
                ('linkcode', models.TextField(blank=True, max_length=20, null=True)),
                ('estsize', models.IntegerField()),
                ('thiskey', models.IntegerField()),
                ('parentkey', models.IntegerField()),
                ('groupnum', models.IntegerField()),
                ('mequivid', models.IntegerField()),
                ('instid', models.IntegerField()),
            ],
        ),
    ]
