# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20170930_1420'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timetable',
            table='NOSH_CMIS_TIMETABLE',
        ),
    ]
