# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_modulegroups_modulegroupsa_modulegroupsb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('courseid', models.TextField(max_length=12)),
                ('name', models.TextField(max_length=80)),
                ('category', models.TextField(max_length=10)),
                ('type', models.TextField(max_length=10)),
                ('linkcode', models.TextField(max_length=20)),
                ('owner', models.TextField(max_length=10)),
                ('numyears', models.IntegerField()),
                ('crsweight', models.FloatField(blank=True, null=True)),
                ('minmodules', models.IntegerField(blank=True, null=True)),
                ('maxmodules', models.IntegerField(blank=True, null=True)),
                ('numplaces', models.IntegerField(blank=True, null=True)),
                ('mintotal', models.IntegerField(blank=True, null=True)),
                ('maxtotal', models.IntegerField(blank=True, null=True)),
                ('firstyear', models.IntegerField(blank=True, null=True)),
                ('oldcourseid', models.TextField(blank=True, max_length=12, null=True)),
                ('isactive', models.CharField(blank=True, max_length=1, null=True)),
                ('lecturerid', models.TextField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.TextField(max_length=10)),
                ('courseid', models.TextField(max_length=12)),
                ('name', models.TextField(max_length=80)),
                ('category', models.TextField(max_length=10)),
                ('type', models.TextField(max_length=10)),
                ('linkcode', models.TextField(max_length=20)),
                ('owner', models.TextField(max_length=10)),
                ('numyears', models.IntegerField()),
                ('crsweight', models.FloatField(blank=True, null=True)),
                ('minmodules', models.IntegerField(blank=True, null=True)),
                ('maxmodules', models.IntegerField(blank=True, null=True)),
                ('numplaces', models.IntegerField(blank=True, null=True)),
                ('mintotal', models.IntegerField(blank=True, null=True)),
                ('maxtotal', models.IntegerField(blank=True, null=True)),
                ('firstyear', models.IntegerField(blank=True, null=True)),
                ('oldcourseid', models.TextField(blank=True, max_length=12, null=True)),
                ('isactive', models.CharField(blank=True, max_length=1, null=True)),
                ('lecturerid', models.TextField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
