# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-20 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_coursea_courseb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulegroupsa',
            name='csize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsa',
            name='estsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsa',
            name='groupnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsa',
            name='maxsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsa',
            name='mequivid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsa',
            name='minsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsa',
            name='parentkey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsa',
            name='prefmaxsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsa',
            name='thiskey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='csize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='estsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='groupnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='maxsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='mequivid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='minsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='parentkey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='prefmaxsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modulegroupsb',
            name='thiskey',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
