# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-30 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20170930_1422'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ccalmaps',
            table='NOSH_CMIS_CCALMAPS',
        ),
        migrations.AlterModelTable(
            name='classgrps',
            table='NOSH_CMIS_CLASSGRPS',
        ),
        migrations.AlterModelTable(
            name='classifications',
            table='NOSH_CMIS_CLASSIFICATIONS',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='NOSH_CMIS_CONTACT',
        ),
        migrations.AlterModelTable(
            name='course',
            table='NOSH_CMIS_COURSE',
        ),
        migrations.AlterModelTable(
            name='crsavailmodules',
            table='NOSH_CMIS_CRSAVAILMODULES',
        ),
        migrations.AlterModelTable(
            name='crscompmodules',
            table='NOSH_CMIS_CRSCOMPMODULES',
        ),
        migrations.AlterModelTable(
            name='depts',
            table='NOSH_CMIS_DEPTS',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='NOSH_CMIS_EQUIPMENT',
        ),
        migrations.AlterModelTable(
            name='features',
            table='NOSH_CMIS_FEATURES',
        ),
        migrations.AlterModelTable(
            name='lecturer',
            table='NOSH_CMIS_LECTURER',
        ),
        migrations.AlterModelTable(
            name='module',
            table='NOSH_CMIS_MODULE',
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='NOSH_CMIS_ROOMS',
        ),
        migrations.AlterModelTable(
            name='sites',
            table='NOSH_CMIS_SITES',
        ),
        migrations.AlterModelTable(
            name='slotdetails',
            table='NOSH_CMIS_SLOTDETAILS',
        ),
        migrations.AlterModelTable(
            name='sources',
            table='NOSH_CMIS_SOURCES',
        ),
        migrations.AlterModelTable(
            name='students',
            table='NOSH_CMIS_STUDENTS',
        ),
        migrations.AlterModelTable(
            name='stumodules',
            table='NOSH_CMIS_STUMODULES',
        ),
        migrations.AlterModelTable(
            name='weekmapnumeric',
            table='NOSH_CMIS_WEEKMAPNUMERIC',
        ),
        migrations.AlterModelTable(
            name='weekmapstring',
            table='NOSH_CMIS_WEEKMAPSTRING',
        ),
        migrations.AlterModelTable(
            name='weekstructure',
            table='NOSH_CMIS_WEEKSTRUCTURE',
        ),
    ]
