# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 17:35
from __future__ import unicode_literals

import os

from django.db import migrations


class Migration(migrations.Migration):

    path_to_sql = os.path.join(
        os.path.dirname(os.path.dirname(os.path.realpath(__file__))),
        'sql',
        'generate_student_timetable.sql'
    )

    with open(path_to_sql, 'r') as sql_file:
        sql_script = sql_file.read()

    dependencies = [
        ('timetable', '0010_auto_20190220_1835'),
    ]

    operations = [
        migrations.RunSQL(
            'DROP FUNCTION IF EXISTS get_student_timetable(TEXT, TEXT, TEXT, TEXT);',
            hints={"type": "raw_sql"}
        ),
        migrations.RunSQL(
            sql_script,
            hints={"type": "raw_sql"}
        )
    ]
