# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 17:35
from __future__ import unicode_literals

import os

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('timetable', '0010_auto_20190220_1835'),
    ]

    path_to_sql = os.path.join(
        os.path.dirname(os.path.dirname(os.path.realpath(__file__))),
        'sql',
        'generate_student_timetable_template.sql'
    )

    with open(path_to_sql, 'r') as sql_file:
        template = sql_file.read()

    # Replace JinjaSQL with manual implementation due to outdated library
    # has no impact in this regard as all use the sqlsafe keyword, and thus
    # are not escaped
    query_a = template.replace("{{ bucket_id | sqlsafe }}", "a")
    query_b = template.replace("{{ bucket_id | sqlsafe }}", "b")

    operations = [
        migrations.RunSQL(
            'DROP FUNCTION IF EXISTS get_student_timetable_a(TEXT, TEXT);',
            hints={"type": "raw_sql"}
        ),
        migrations.RunSQL(
            'DROP FUNCTION IF EXISTS get_student_timetable_b(TEXT, TEXT);',
            hints={"type": "raw_sql"}
        ),
        migrations.RunSQL(
            query_a,
            hints={"type": "raw_sql"}
        ),
        migrations.RunSQL(
            query_b,
            hints={"type": "raw_sql"}
        ),
    ]
