# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-23 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_stuclasses_stuclassesa_stuclassesb'),
        ('timetable', '0008_auto_20190221_1324'),
    ]

    operations = [
    ]
