# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-02 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_merge_20190223_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturera',
            name='category',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturera',
            name='costtype',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturera',
            name='lecturerid',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturera',
            name='parttime',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lecturera',
            name='status',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturera',
            name='type',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturera',
            name='linkcode',
            field=models.TextField(max_length=20, null=True, blank=True)
        ),
        migrations.AlterField(
            model_name='lecturerb',
            name='category',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerb',
            name='costtype',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerb',
            name='parttime',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerb',
            name='status',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerb',
            name='type',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerb',
            name='linkcode',
            field=models.TextField(max_length=20, null=True, blank=True)
        ),
    ]
