# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_auto_20190305_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableb',
            name='clsgrpcode',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='deptid',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='lecturerid',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='modgrpcode',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='moduleid',
            field=models.TextField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='moduletype',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='roomgrpcode',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='roomid',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='siteid',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
