# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-08 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_crsavailmodulesa_crsavailmodulesb_crscompmodulesa_crscompmodulesb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsa',
            name='courseid',
            field=models.TextField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='studentsb',
            name='courseid',
            field=models.TextField(max_length=12, null=True),
        ),
    ]
