# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_auto_20190908_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsa',
            name='linkcode',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentsb',
            name='linkcode',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
