# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0016_auto_20190305_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablea',
            name='starttime',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='starttime',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
