# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20190305_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablea',
            name='finishtime',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='finishtime',
            field=models.TextField(max_length=5, null=True),
        ),
    ]
