# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_auto_20191002_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationsA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.CharField(max_length=10, null=True)),
                ('classid', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=55, null=True)),
                ('description', models.CharField(max_length=120, null=True)),
                ('linkcode', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationsB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setid', models.CharField(max_length=10, null=True)),
                ('classid', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=55, null=True)),
                ('description', models.CharField(max_length=120, null=True)),
                ('linkcode', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
