# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_auto_20190305_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetablea',
            name='userchange',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timetableb',
            name='userchange',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
