# Generated by Django 2.2.10 on 2020-03-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_classificationsa_classificationsb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
