# Generated by Django 3.2.23 on 2024-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0019_delete_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsa',
            name='field1',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='studentsa',
            name='field2',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='studentsb',
            name='field1',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='studentsb',
            name='field2',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
