# Generated by Django 2.2.17 on 2020-12-16 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReplacements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('old_hardware_id', models.IntegerField()),
                ('old_survey_device_id', models.IntegerField()),
                ('old_survey_id', models.IntegerField()),
                ('new_hardware_id', models.IntegerField()),
                ('new_survey_device_id', models.IntegerField()),
                ('new_survey_id', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('hardware_id', models.IntegerField()),
                ('survey_device_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('sensor_id', 'survey_id')},
            },
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                # It is not possible to have a composite primary key yet
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('state', models.IntegerField()),
            ],
            options={
                'unique_together': {('sensor_id', 'survey_id', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='SurveyChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.IntegerField()),
                ('old_name', models.TextField(null=True)),
                ('old_start_datetime', models.DateTimeField(null=True)),
                ('old_end_datetime', models.DateTimeField(null=True)),
                ('old_active', models.BooleanField(null=True)),
                ('new_name', models.TextField()),
                ('new_start_datetime', models.DateTimeField()),
                ('new_end_datetime', models.DateTimeField()),
                ('new_active', models.BooleanField()),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
