# Generated by Django 2.2.17 on 2021-01-31 10:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('survey_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorReplacements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('hardware_id', models.IntegerField()),
                ('survey_device_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Surveys')),
                ('name', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('state', models.IntegerField()),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('survey_id', models.IntegerField()),
                ('hardware_id', models.IntegerField()),
                ('survey_device_id', models.IntegerField()),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.AddConstraint(
            model_name='historical',
            constraint=models.UniqueConstraint(
                fields=('sensor_id', 'survey_id', 'datetime'), name='historical_composite_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='sensors',
            constraint=models.UniqueConstraint(fields=('sensor_id', 'survey_id'),
                                               name='sensors_composite_primary_key'),
        ),
        migrations.RenameField(
            model_name='surveychanges',
            old_name='survey_id',
            new_name='survey',
        ),
    ]
