# Generated by Django 2.2.17 on 2020-12-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreplacements',
            old_name='old_hardware_id',
            new_name='hardware_id',
        ),
        migrations.RenameField(
            model_name='sensorreplacements',
            old_name='old_survey_device_id',
            new_name='survey_device_id',
        ),
        migrations.RenameField(
            model_name='sensorreplacements',
            old_name='old_survey_id',
            new_name='survey_id',
        ),
        migrations.RenameField(
            model_name='surveychanges',
            old_name='new_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='surveychanges',
            old_name='new_end_datetime',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='surveychanges',
            old_name='new_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='surveychanges',
            old_name='new_start_datetime',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='sensorreplacements',
            name='new_hardware_id',
        ),
        migrations.RemoveField(
            model_name='sensorreplacements',
            name='new_survey_device_id',
        ),
        migrations.RemoveField(
            model_name='sensorreplacements',
            name='new_survey_id',
        ),
        migrations.RemoveField(
            model_name='surveychanges',
            name='old_active',
        ),
        migrations.RemoveField(
            model_name='surveychanges',
            name='old_end_datetime',
        ),
        migrations.RemoveField(
            model_name='surveychanges',
            name='old_name',
        ),
        migrations.RemoveField(
            model_name='surveychanges',
            name='old_start_datetime',
        ),
        migrations.AlterField(
            model_name='surveychanges',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.Surveys'),
        ),
        migrations.AlterUniqueTogether(
            name='historical',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sensors',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='historical',
            constraint=models.UniqueConstraint(
                fields=('sensor_id', 'survey_id', 'datetime'), name='historical_composite_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='sensors',
            constraint=models.UniqueConstraint(fields=('sensor_id', 'survey_id'),
                                               name='sensors_composite_primary_key'),
        ),
    ]
