# Generated by Django 2.2.17 on 2021-05-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historical',
            options={'ordering': ['survey_id', 'sensor_id', 'datetime']},
        ),
        migrations.AlterModelOptions(
            name='sensors',
            options={'ordering': ['survey_id', 'sensor_id']},
        ),
        migrations.AlterModelOptions(
            name='surveys',
            options={'ordering': ['survey_id']},
        ),
        migrations.AddIndex(
            model_name='historical',
            index=models.Index(fields=['survey_id', 'datetime'], name='workspaces__survey__00af05_idx'),
        ),
        migrations.AddIndex(
            model_name='historical',
            index=models.Index(fields=['survey_id', 'sensor_id', 'datetime'], name='workspaces__survey__4c11e3_idx'),
        ),
    ]
