# Generated by Django 2.2.17 on 2020-12-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_auto_20201221_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveychanges',
            old_name='survey_id',
            new_name='survey',
        ),
    ]
