# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import roombookings.api_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('roomid', models.CharField(blank=True, max_length=160, null=True)),
                ('sitename', models.CharField(blank=True, max_length=320, null=True)),
                ('roomname', models.CharField(blank=True, max_length=320, null=True)),
                ('bookabletype', models.CharField(blank=True, max_length=40, null=True)),
                ('slotid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bookingid', models.CharField(blank=True, max_length=80, null=True)),
                ('starttime', models.CharField(blank=True, max_length=80, null=True)),
                ('finishtime', models.CharField(blank=True, max_length=20, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, null=True)),
                ('finishdatetime', models.DateTimeField(blank=True, null=True)),
                ('weeknumber', models.FloatField(blank=True, null=True)),
                ('condisplayname', models.CharField(blank=True, max_length=4000, null=True)),
                ('phone', models.CharField(blank=True, max_length=160, null=True)),
                ('descrip', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'CMIS_UCLAPI_V_BOOKINGS',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('roomid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('units', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=320, null=True)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'CMIS_UCLAPI_V_EQUIP_FEATURES',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('sitename', models.CharField(blank=True, max_length=320, null=True)),
                ('address1', models.CharField(blank=True, max_length=320, null=True)),
                ('address2', models.CharField(blank=True, max_length=320, null=True)),
                ('address3', models.CharField(blank=True, max_length=320, null=True)),
                ('address4', models.CharField(blank=True, max_length=320, null=True)),
                ('roomid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('roomname', models.CharField(blank=True, max_length=320, null=True)),
                ('roomdeptid', models.CharField(blank=True, max_length=40, null=True)),
                ('bookabletype', models.CharField(blank=True, max_length=40, null=True)),
                ('roomclass', models.CharField(blank=True, max_length=40, null=True)),
                ('zone', models.CharField(blank=True, max_length=40, null=True)),
                ('webview', models.CharField(blank=True, max_length=4, null=True)),
                ('automated', models.CharField(blank=True, max_length=4, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'CMIS_UCLAPI_V_ROOMS',
            },
        ),
        migrations.CreateModel(
            name='PageToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_token', models.CharField(default=roombookings.api_helpers.generate_token, max_length=2000, unique=True)),
                ('pagination', models.IntegerField(default=20)),
                ('query', models.CharField(max_length=100000)),
                ('curr_page', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
