# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('roomid', models.CharField(blank=True, max_length=40, null=True)),
                ('sitename', models.CharField(blank=True, max_length=320, null=True)),
                ('roomname', models.CharField(blank=True, max_length=320, null=True)),
                ('roomdeptid', models.CharField(blank=True, max_length=40, null=True)),
                ('bookabletype', models.CharField(blank=True, max_length=40, null=True)),
                ('roomclass', models.CharField(blank=True, max_length=40, null=True)),
                ('zone', models.CharField(blank=True, max_length=40, null=True)),
                ('webview', models.CharField(blank=True, max_length=4, null=True)),
                ('automated', models.CharField(blank=True, max_length=4, null=True)),
                ('slotid', models.BigIntegerField(blank=True, null=True)),
                ('bookingid', models.CharField(blank=True, max_length=80, null=True)),
                ('starttime', models.CharField(blank=True, max_length=20, null=True)),
                ('finishtime', models.CharField(blank=True, max_length=20, null=True)),
                ('startdatetime', models.DateField(blank=True, null=True)),
                ('finishdatetime', models.DateField(blank=True, null=True)),
                ('weekday', models.BigIntegerField(blank=True, null=True)),
                ('dayname', models.CharField(blank=True, max_length=144, null=True)),
                ('weekid', models.BigIntegerField(blank=True, null=True)),
                ('weeknumber', models.FloatField(blank=True, null=True)),
                ('mapdate', models.DateField(blank=True, null=True)),
                ('lecturerid', models.CharField(blank=True, max_length=40, null=True)),
                ('lecturername', models.CharField(blank=True, max_length=4000, null=True)),
                ('contactid', models.CharField(blank=True, max_length=40, null=True)),
                ('contactname', models.CharField(blank=True, max_length=320, null=True)),
                ('contype', models.CharField(blank=True, max_length=40, null=True)),
                ('contactused', models.CharField(blank=True, max_length=32, null=True)),
                ('condisplayname', models.CharField(blank=True, max_length=4000, null=True)),
                ('phone', models.CharField(blank=True, max_length=160, null=True)),
                ('exdirectory', models.CharField(blank=True, max_length=4, null=True)),
                ('firstmodid', models.CharField(blank=True, max_length=48, null=True)),
                ('firstmodgrp', models.CharField(blank=True, max_length=40, null=True)),
                ('firstmodname', models.CharField(blank=True, max_length=480, null=True)),
                ('gendatastring', models.CharField(blank=True, max_length=400, null=True)),
                ('descrip', models.CharField(blank=True, max_length=400, null=True)),
                ('title', models.CharField(blank=True, max_length=532, null=True)),
                ('classid', models.CharField(blank=True, max_length=40, null=True)),
                ('eventtype', models.CharField(blank=True, max_length=220, null=True)),
                ('closed', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.BigIntegerField(blank=True, null=True)),
                ('cancelled', models.CharField(blank=True, max_length=4, null=True)),
                ('provisional', models.CharField(blank=True, max_length=4, null=True)),
                ('modslotentry', models.BigIntegerField(blank=True, null=True)),
                ('moduleid', models.CharField(blank=True, max_length=48, null=True)),
                ('modgrpcode', models.CharField(blank=True, max_length=40, null=True)),
                ('modulename', models.CharField(blank=True, max_length=480, null=True)),
                ('datestring', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'CMIS_V_DIARYINFO',
            },
        ),
    ]
