# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, max_length=320, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('classification', models.CharField(blank=True, max_length=40, null=True)),
                ('roomgrpcode', models.CharField(blank=True, max_length=40, null=True)),
                ('zone', models.CharField(blank=True, max_length=40, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('prefmin', models.FloatField(blank=True, null=True)),
                ('prefmax', models.FloatField(blank=True, null=True)),
                ('deptid', models.CharField(blank=True, max_length=40, null=True)),
                ('roomarea', models.FloatField(blank=True, null=True)),
                ('dynafill', models.CharField(blank=True, max_length=4, null=True)),
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('uniquefield', models.CharField(blank=True, max_length=40, null=True)),
                ('linkcode', models.CharField(blank=True, max_length=80, null=True)),
                ('campusid', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
    ]
