# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import roombookings.api_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_token', models.CharField(default=roombookings.api_helpers.generate_token, max_length=2000, unique=True)),
                ('pagination', models.IntegerField(default=20)),
                ('query', models.CharField(max_length=100000)),
                ('curr_page', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
