# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0004_equipment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='CMIS_UCLAPI_V_BOOKINGS',
        ),
        migrations.AlterModelTable(
            name='room',
            table='CMIS_UCLAPI_V_ROOMS',
        ),
    ]
