# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0004_equipment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipment',
            table='"CMIS_UCLAPI_V_EQUIP_FEATURES"',
        ),
    ]
