# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0005_auto_20170216_1124'),
        ('roombookings', '0006_cmisuclapivequipfeatures'),
    ]

    operations = [
    ]
