# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0006_bookinga_bookingb_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteid', models.CharField(max_length=40)),
                ('roomid', models.CharField(max_length=40)),
                ('lat', models.CharField(max_length=30)),
                ('lng', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('siteid', 'roomid')]),
        ),
    ]
