# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0007_auto_20170327_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinga',
            name='slotid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookingb',
            name='slotid',
            field=models.BigIntegerField(),
        ),
    ]
    