# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-26 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0007_auto_20170328_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinga',
            name='title',
            field=models.CharField(blank=True, max_length=523, null=True),
        ),
        migrations.AddField(
            model_name='bookingb',
            name='title',
            field=models.CharField(blank=True, max_length=523, null=True),
        ),
    ]
