# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0007_auto_20170328_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCache',
            fields=[
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('roomid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('units', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=320, null=True)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('type', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCache',
            fields=[
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('sitename', models.CharField(blank=True, max_length=320, null=True)),
                ('address1', models.CharField(blank=True, max_length=320, null=True)),
                ('address2', models.CharField(blank=True, max_length=320, null=True)),
                ('address3', models.CharField(blank=True, max_length=320, null=True)),
                ('address4', models.CharField(blank=True, max_length=320, null=True)),
                ('roomid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('roomname', models.CharField(blank=True, max_length=320, null=True)),
                ('roomdeptid', models.CharField(blank=True, max_length=40, null=True)),
                ('bookabletype', models.CharField(blank=True, max_length=40, null=True)),
                ('roomclass', models.CharField(blank=True, max_length=40, null=True)),
                ('zone', models.CharField(blank=True, max_length=40, null=True)),
                ('webview', models.CharField(blank=True, max_length=4, null=True)),
                ('automated', models.CharField(blank=True, max_length=4, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
