# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-21 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombookings', '0010_delete_pagetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('sitename', models.CharField(blank=True, max_length=320, null=True)),
                ('address1', models.CharField(blank=True, max_length=320, null=True)),
                ('address2', models.CharField(blank=True, max_length=320, null=True)),
                ('address3', models.CharField(blank=True, max_length=320, null=True)),
                ('address4', models.CharField(blank=True, max_length=320, null=True)),
                ('roomid', models.CharField(max_length=40)),
                ('roomname', models.CharField(blank=True, max_length=320, null=True)),
                ('roomdeptid', models.CharField(blank=True, max_length=40, null=True)),
                ('bookabletype', models.CharField(blank=True, max_length=40, null=True)),
                ('roomclass', models.CharField(blank=True, max_length=40, null=True)),
                ('zone', models.CharField(blank=True, max_length=40, null=True)),
                ('webview', models.CharField(blank=True, max_length=4, null=True)),
                ('automated', models.CharField(blank=True, max_length=4, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setid', models.CharField(blank=True, max_length=40, null=True)),
                ('siteid', models.CharField(blank=True, max_length=40, null=True)),
                ('sitename', models.CharField(blank=True, max_length=320, null=True)),
                ('address1', models.CharField(blank=True, max_length=320, null=True)),
                ('address2', models.CharField(blank=True, max_length=320, null=True)),
                ('address3', models.CharField(blank=True, max_length=320, null=True)),
                ('address4', models.CharField(blank=True, max_length=320, null=True)),
                ('roomid', models.CharField(max_length=40)),
                ('roomname', models.CharField(blank=True, max_length=320, null=True)),
                ('roomdeptid', models.CharField(blank=True, max_length=40, null=True)),
                ('bookabletype', models.CharField(blank=True, max_length=40, null=True)),
                ('roomclass', models.CharField(blank=True, max_length=40, null=True)),
                ('zone', models.CharField(blank=True, max_length=40, null=True)),
                ('webview', models.CharField(blank=True, max_length=4, null=True)),
                ('automated', models.CharField(blank=True, max_length=4, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
