# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('raw_request', models.TextField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('api_token', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=1000)),
                ('given_name', models.CharField(max_length=100)),
                ('cn', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=1000)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('raw_intranet_groups', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='apicall',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_call', to='dashboard.App'),
        ),
        migrations.AddField(
            model_name='apicall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_call', to='dashboard.User'),
        ),
    ]
