# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 17:23
from __future__ import unicode_literals

import dashboard.app_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='api_token',
            field=models.CharField(default=dashboard.app_helpers.generate_api_token, max_length=1000, unique=True),
        ),
    ]
