# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
