# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 14:45
from __future__ import unicode_literals

import dashboard.app_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryToken',
            fields=[
                ('id', models.CharField(default=dashboard.app_helpers.generate_app_id, max_length=20, primary_key=True, serialize=False)),
                ('api_token', models.CharField(default=dashboard.app_helpers.generate_api_token, max_length=1000, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uses', models.IntegerField(default=0)),
            ],
        ),
    ]
