# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 20:14
from __future__ import unicode_literals

import dashboard.app_helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='client_id',
            field=models.CharField(default=dashboard.app_helpers.generate_app_client_id, max_length=33, unique=True),
        ),
        migrations.AddField(
            model_name='app',
            name='client_secret',
            field=models.CharField(default=dashboard.app_helpers.generate_app_client_secret, max_length=64, unique=True),
        ),
    ]
