# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_user_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('siteid', models.CharField(blank=True, max_length=40)),
                ('roomid', models.CharField(blank=True, max_length=160)),
                ('contact', models.CharField(blank=True, max_length=4000)),
                ('last_fired', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.App')),
            ],
        ),
    ]
