# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170516_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='callback_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
