# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_temporarytoken'),
        ('dashboard', '0006_user_agreement'),
    ]

    operations = [
    ]
