# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_webhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='last_fired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
