# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_merge_20170605_1150'),
        ('dashboard', '0007_auto_20170603_1654'),
    ]

    operations = [
    ]
