# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTriggerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=10000000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='webhook',
            name='ownership_verification_secret',
            field=models.CharField(default='default_secret', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhook',
            name='ownership_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhooktriggerhistory',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Webhook'),
        ),
    ]
