# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 16:26
from __future__ import unicode_literals

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('dashboard', '0008_auto_20170701_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='scope',
            field=models.ForeignKey(default=dashboard.models.App.create_scope, on_delete=django.db.models.deletion.CASCADE, to='oauth.OAuthScope'),
        ),
    ]
