# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_user_agreement'),
        ('dashboard', '0008_app_scope'),
    ]

    operations = [
    ]
