# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_temporarytoken'),
        ('dashboard', '0009_merge_20170518_2222'),
    ]

    operations = [
    ]
