# Generated by Django 2.2.13 on 2020-07-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_delete_temporarytoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quota',
            field=models.IntegerField(default=10000),
        ),
    ]
