# Generated by Django 2.2.13 on 2020-06-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_oauthtoken_active'),
        ('dashboard', '0014_auto_20200727_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicall',
            name='raw_request',
        ),
        migrations.AddField(
            model_name='apicall',
            name='method',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apicall',
            name='queryparams',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='apicall',
            name='service',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apicall',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_call', to='oauth.OAuthToken'),
        ),
        migrations.AddField(
            model_name='apicall',
            name='token_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
