# Generated by Django 2.2.13 on 2020-07-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_user_quota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='quota',
            new_name='dev_quota',
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_quota',
            field=models.IntegerField(default=10000),
        ),
    ]
