# Generated by Django 2.2.17 on 2021-06-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20201229_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
