# Generated by Django 2.2.24 on 2021-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20201229_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhooktriggerhistory',
            name='status_code',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
