# Generated by Django 2.2.24 on 2021-08-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('dashboard', '0018_auto_20210625_0714'), ('dashboard', '0019_auto_20210626_1811'), ('dashboard', '0020_auto_20210626_1812'), ('dashboard', '0021_auto_20210627_1527')]

    dependencies = [
        ('dashboard', '0017_webhook_last_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='last_success',
        ),
    ]
