# Generated by Django 3.2.13 on 2023-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_webhook_last_success_squashed_0019_webhooktriggerhistory_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unscoped_affiliation',
        ),
        migrations.AddField(
            model_name='user',
            name='user_types',
            field=models.CharField(default='', max_length=200),
        ),
    ]
