# Generated by Django 3.2.13 on 2023-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20230117_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='raw_intranet_groups',
            field=models.TextField(),
        ),
    ]
