version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/frontend"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
  - package_manager: "python"
    directory: "/backend/uclapi"
    update_schedule: "live"
#    automerged_updates:
#      - match:
#          dependency_type: "development" # requirements-dev.txt
#          update_type: "semver:minor"
#      - match:
#          dependency_type: "production" # requirements.txt
#          update_type: "semver:patch"
