# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import oauth.app_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='token',
            field=models.CharField(default=oauth.app_helpers.generate_user_token, max_length=75, unique=True),
        ),
    ]
