# Generated by Django 2.2.13 on 2020-07-01 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_oauthtoken_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthtoken',
            name='creation_date',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
