# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20170602_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthscope',
            name='private_roombookings',
        ),
        migrations.RemoveField(
            model_name='oauthscope',
            name='private_timetable',
        ),
        migrations.RemoveField(
            model_name='oauthscope',
            name='private_uclu',
        ),
        migrations.AddField(
            model_name='oauthscope',
            name='scope_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
