name: Auto Merge Approved Dependabot

on: workflow_dispatch

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Run helper function
      run: unset GITHUB_TOKEN &&
           echo ${{secrets.PERSONAL_DEPENDABOT_GITHUB_TOKEN}} | gh auth login --with-token && 
           python .github/helpers/auto-merge-approved-dependabot.py
      env:
        GITHUB_TOKEN: ${{secrets.PERSONAL_DEPENDABOT_GITHUB_TOKEN}}
